### ISSUE TITLE
VS 2017 'Could not load file or assembly 'FSharp.Core, Version=4.4.1.0

### ISSUE THREAD

**Issue by makslevental** [ChrisMarinos/FSharpKoans#58]
System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  Source=mscorlib
  StackTrace:
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.AppDomain.GetTargetFrameworkName()

**Comment by makslevental** [comment]
same problem in vs 2015

**Comment by makslevental** [comment]
nm recloning fixes in both version

**Comment by Arrow7000** [comment]
I'm getting the same error in VS 2017. I'm new to using Visual Studio. How do I 'reclone'?

**Comment by Arrow7000** [comment]
I just fixed it. I had to update the F# version by navigating to `Project > FSharpKoans Properties` and then in the Application tab selecting the F# 4.1 target runtime.

![2017-11-15_11-21-57](https://user-images.githubusercontent.com/13225609/32833705-aa7c97dc-c9f7-11e7-91f9-7852c76881f5.png)
